package view;

import control.actionListener.AddNewPropertyActionListener;
import control.actionListener.LogoutActionListener;
import control.actionListener.ManagePropertyActionListener;

import javax.swing.*;

/**
 *
 * @author husam
 */
public class AgentHomePage extends javax.swing.JPanel {

    /**
     * Creates new form AgentHomepage
     */
    public AgentHomePage() {
        //LookAndFeel.getLookAndFeel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        addNewPropertyButton = new javax.swing.JButton();
        ManagePropertyButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        managePropertyLabel = new javax.swing.JLabel();
        addNewPropertyLabel = new javax.swing.JLabel();


        //action Listener
        addNewPropertyButton.addActionListener(new AddNewPropertyActionListener());
        ManagePropertyButton.addActionListener(new ManagePropertyActionListener());
        logoutButton.addActionListener(new LogoutActionListener());


        setBackground(new java.awt.Color(255, 255, 255));

        addNewPropertyButton.setBackground(new java.awt.Color(255, 255, 255));
        addNewPropertyButton.setIcon(new ImageIcon(getClass().getResource("/assets/images/house.png"))); // NOI18N
        addNewPropertyButton.setBorder(null);

        ManagePropertyButton.setBackground(new java.awt.Color(255, 255, 255));
        ManagePropertyButton.setIcon(new ImageIcon(getClass().getResource("/assets/images/update.png"))); // NOI18N
        ManagePropertyButton.setBorder(null);
        ManagePropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagePropertyButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/logout.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(10, 72, 194));
        jLabel1.setLabelFor(logoutButton);
        jLabel1.setText("Logout");

        managePropertyLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        managePropertyLabel.setForeground(new java.awt.Color(255, 51, 102));
        managePropertyLabel.setLabelFor(ManagePropertyButton);
        managePropertyLabel.setText("Manage Poperty");

        addNewPropertyLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addNewPropertyLabel.setForeground(new java.awt.Color(255, 102, 102));
        addNewPropertyLabel.setLabelFor(addNewPropertyLabel);
        addNewPropertyLabel.setText("Add new prperty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addNewPropertyButton)
                                        .addComponent(addNewPropertyLabel))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(managePropertyLabel)
                                        .addComponent(ManagePropertyButton))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(121, 121, 121)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(logoutButton)))
                                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ManagePropertyButton)
                                        .addComponent(addNewPropertyButton)
                                        .addComponent(logoutButton))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(managePropertyLabel)
                                        .addComponent(addNewPropertyLabel)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ManagePropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton ManagePropertyButton;
    private javax.swing.JButton addNewPropertyButton;
    private javax.swing.JLabel addNewPropertyLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel managePropertyLabel;
    // End of variables declaration
}