package view;

///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template modle.file, choose Tools | Templates
// * and open the template in the editor.
// */
//
//import control.LoginController;
//import control.Session;
//import control.actionListener.loginListener;
//
//import *;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//
///**
// *
// * @author husam
// */
//public class LoginPage extends JPanel {
////loginButton.addActionListener(new loginListener(this));
//    /**
//     * Creates new form Login
//     */
//    public LoginPage() {
//        LookAndFeel.getLookAndFeel();
//        initComponents();
//    }
//
//    public JPasswordField getPasswordfild() {
//        return passwordfild;
//    }
//
//    public JTextField getUserNameTextField() {
//        return userNameTextField;
//    }
//
//    public JPanel getjPanel1() {
//        return this;
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//       // jPanel1 = new JPanel();
//        passwordfild = new JPasswordField();
//        userNameTextField = new JTextField();
//        loginButton = new JButton();
//        loginLabel = new JLabel();
//
////        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
////        setBackground(new java.awt.Color(255, 255, 255));
//
//        setForeground(new java.awt.Color(255, 255, 255));
//
//        loginButton.setText("Login");
//
//        loginLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
//        loginLabel.setForeground(new java.awt.Color(172, 198, 94));
//        loginLabel.setText("Login");
//loginButton.addActionListener(new loginListener(this));
//        GroupLayout jPanel1Layout = new GroupLayout(this);
//        setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
//                                        .addComponent(userNameTextField, GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
//                                        .addComponent(passwordfild))
//                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGap(122, 122, 122)
//                                .addComponent(loginButton)
//                                .addContainerGap(136, Short.MAX_VALUE))
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGap(130, 130, 130)
//                                .addComponent(loginLabel, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
//                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGap(30, 30, 30)
//                                .addComponent(loginLabel, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(userNameTextField, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(passwordfild, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(loginButton)
//                                .addContainerGap(75, Short.MAX_VALUE))
//        );
//
////        GroupLayout layout = new GroupLayout(getContentPane());
////        getContentPane().setLayout(layout);
////        layout.setHorizontalGroup(
////                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
////                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
////                                .addContainerGap(94, Short.MAX_VALUE)
////                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
////                                .addGap(88, 88, 88))
////        );
////        layout.setVerticalGroup(
////                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
////                        .addGroup(layout.createSequentialGroup()
////                                .addGap(111, 111, 111)
////                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
////                                .addContainerGap(116, Short.MAX_VALUE))
////        );
////
////        pack();
//    }// </editor-fold>
//    // Variables declaration - do not modify
//   // private JPanel jPanel1;
//    private JButton loginButton;
//    private JLabel loginLabel;
//    private JPasswordField passwordfild;
//    private JTextField userNameTextField;
//
////    @Override
////    public void actionPerformed(ActionEvent e) {
////         Session.setUser(LoginController.login(this));
////         if (!Session.isEmpty()) {
////          jPanel1.setVisible(false);
////          AddProperty property=new AddProperty();
////          this.add(property);
////             invalidate();
////             validate();
////             repaint();
////         }
////    }
//    // End of variables declaration
//}














/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template modle.file, choose Tools | Templates
 * and open the template in the editor.
 */

import control.LoginController;
import control.Session;
import control.actionListener.ViewRegisterPageAction;
import control.actionListener.loginListener;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class LoginPage extends JPanel {
    private JButton loginButton;
    private JLabel loginLabel;
    private JPasswordField passwordfild;
    private JButton registerButton;
    private JTextField userNameTextField;

    public LoginPage() {
        LookAndFeel.getLookAndFeel();
        initComponents();
    }

    public JPasswordField getPasswordfild() {
        return passwordfild;
    }

    public JTextField getUserNameTextField() {
        return userNameTextField;
    }

    public JPanel getjPanel1() {
        return this;
    }
    private void initComponents() {
        loginLabel = new JLabel();
        userNameTextField = new JTextField();
        passwordfild = new JPasswordField();
        loginButton = new JButton();
        registerButton = new JButton();
        setLayout(null);

        loginLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(172, 198, 94));
        loginLabel.setText("Login");
        loginButton.addActionListener(new loginListener(this));
        add(loginLabel);
        loginLabel.setBounds(140, 20, 63, 25);

        add(userNameTextField);
        userNameTextField.setBounds(80, 70, 180, 30);
        add(passwordfild);
        passwordfild.setBounds(80, 120, 180, 29);

        loginButton.setText("Login");
        add(loginButton);
        loginButton.setBounds(130, 170, 73, 25);

        registerButton.setBackground(new java.awt.Color(255, 255, 255));
        registerButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        registerButton.setText("Register");
        registerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerButton.addActionListener(new ViewRegisterPageAction());
        add(registerButton);
        registerButton.setBounds(140, 220, 50, 21);
    }

    }
