package view;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class TestLogin {
    public static void main(String[] args) {

//        JFrame frame=new JFrame();
////        AddProperty obj=new AddProperty();
//        AgentHomePage obj=new AgentHomePage();
//        frame.setSize(800,442);
////        frame.setResizable(false);
//        frame.add(obj);
//        obj.setVisible(true);
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.setLocationRelativeTo(null);
//        frame.setVisible(true);
        ABC a=new ABC();
        a.add(new AddPropertya());

    }
}

class ABC extends JFrame {
    JLabel label;
    public ABC(){
       label=new JLabel("!21");
        //JButton btn=new JButton("click");
        //btn.setSize(150,30);
        //btn.addActionListener(this);
       // add(btn);
       // label.setSize(20,20);
        //add(label);
        //label.setVisible(true);
        setSize(700,700);
        setVisible(true);
    }

}



 class AddPropertya extends javax.swing.JPanel {

    /**
     * Creates new form AddProperty
     */
    public AddPropertya() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        list=new ArrayList<>();
        jTextField1 = new javax.swing.JTextField();
        mainLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        propertyTypeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        prpertyTypeComboBox = new javax.swing.JComboBox<>();
        RooomNoLabel = new javax.swing.JLabel();
        RoomNoSpinner = new javax.swing.JSpinner();
        bathroomNoSpinner = new javax.swing.JSpinner();
        bathroomNoLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        selectImgLabel = new javax.swing.JLabel();
        selectImgButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        descriptionLabel = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        propertySizeLabel = new javax.swing.JLabel();
        propertySizeTextField = new javax.swing.JTextField();
        homeLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        postCodeLabel = new javax.swing.JLabel();
        postCodeTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        cityComboBox = new javax.swing.JComboBox<>();
        removeImageButton = new javax.swing.JButton();
        ImageNoLabel = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 255, 255));
        setName(""); // NOI18N

        mainLabel.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        mainLabel.setForeground(new java.awt.Color(172, 198, 94));
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Add Property");
        mainLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        titleLabel.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(41, 57, 74));
        titleLabel.setLabelFor(titleTextField);
        titleLabel.setText("Title");

        titleTextField.setToolTipText("");
        titleTextField.setName(""); // NOI18N

        propertyTypeLabel.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        propertyTypeLabel.setForeground(new java.awt.Color(41, 57, 74));
        propertyTypeLabel.setText("Prperty Type");

        prpertyTypeComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        prpertyTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RooomNoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        RooomNoLabel.setForeground(new java.awt.Color(41, 57, 74));
        RooomNoLabel.setLabelFor(RoomNoSpinner);
        RooomNoLabel.setText("Room no");

        bathroomNoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bathroomNoLabel.setForeground(new java.awt.Color(41, 57, 74));
        bathroomNoLabel.setLabelFor(bathroomNoSpinner);
        bathroomNoLabel.setText("Bathroom no");

        selectImgLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        selectImgLabel.setForeground(new java.awt.Color(41, 57, 74));
        selectImgLabel.setLabelFor(selectImgButton);
        selectImgLabel.setText("Upload Picture..");

        selectImgButton.setBackground(new java.awt.Color(200, 223, 250));
        selectImgButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        selectImgButton.setForeground(new java.awt.Color(41, 57, 74));
        selectImgButton.setText("Upload");
        selectImgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectImgButtonActionPerformed(evt);
            }
        });

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        descriptionLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(41, 57, 74));
        descriptionLabel.setLabelFor(descriptionTextArea);
        descriptionLabel.setText("Description");

        SaveButton.setBackground(new java.awt.Color(172, 198, 94));
        SaveButton.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(41, 57, 74));
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        addressLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addressLabel.setLabelFor(addressTextField);
        addressLabel.setText("Address");

        propertySizeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        propertySizeLabel.setForeground(new java.awt.Color(41, 57, 74));
        propertySizeLabel.setLabelFor(propertySizeTextField);
        propertySizeLabel.setText("Size");

        propertySizeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySizeTextFieldActionPerformed(evt);
            }
        });

        homeLabel.setForeground(new java.awt.Color(51, 0, 51));
        homeLabel.setText("Home");

        cityLabel.setLabelFor(cityComboBox);
        cityLabel.setText("City");

        postCodeLabel.setLabelFor(postCodeTextField);
        postCodeLabel.setText("Post Code");

        postCodeTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        postCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postCodeTextFieldActionPerformed(evt);
            }
        });

        cityComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        removeImageButton.setBackground(new java.awt.Color(250, 101, 133));
        removeImageButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        removeImageButton.setForeground(new java.awt.Color(255, 255, 255));
        removeImageButton.setText("reomve");
        removeImageButton.setVisible(false);
        ImageNoLabel.setVisible(false);
        removeImageButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        removeImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeImageButtonActionPerformed(evt);
            }
        });

        ImageNoLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RooomNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bathroomNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RoomNoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bathroomNoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(292, Short.MAX_VALUE))
                        .addComponent(jSeparator3)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(descriptionLabel)
                                                .addGap(31, 31, 31))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(cityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(postCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(postCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(50, 50, 50))))
                        .addComponent(jSeparator4)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(82, 82, 82))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(propertySizeLabel)
                                                        .addComponent(propertyTypeLabel))
                                                .addGap(26, 26, 26)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(titleTextField)
                                        .addComponent(prpertyTypeComboBox, 0, 250, Short.MAX_VALUE)
                                        .addComponent(propertySizeTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(209, 209, 209)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(selectImgButton)
                                                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addComponent(selectImgLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ImageNoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeImageButton)
                                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(prpertyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(propertyTypeLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(propertySizeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                                        .addComponent(propertySizeLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(RoomNoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(RooomNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(bathroomNoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(bathroomNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(addressLabel)
                                                        .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(cityLabel)
                                                        .addComponent(postCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(postCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(302, 302, 302)
                                                .addComponent(descriptionLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(selectImgButton)
                                        .addComponent(selectImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(removeImageButton)
                                        .addComponent(ImageNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
        );
    }// </editor-fold>

    private void selectImgButtonActionPerformed(java.awt.event.ActionEvent evt) {

        list.add(1);
        ImageNoLabel.setText(String.valueOf(list.size()));
        if(list.size()>0){
          removeImageButton.setVisible(true);
          ImageNoLabel.setVisible(true);
        }else {
            removeImageButton.setVisible(false);
            ImageNoLabel.setVisible(false);
        }
    }

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void propertySizeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void postCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void removeImageButtonActionPerformed(java.awt.event.ActionEvent evt) {
        list.remove(list.size()-1);
        ImageNoLabel.setText(String.valueOf(list.size()));
        if (list.size()<=0){
            removeImageButton.setVisible(false);
            ImageNoLabel.setVisible(false);
        }
    }


    // Variables declaration - do not modify
     ArrayList<Integer>list;
    private javax.swing.JLabel ImageNoLabel;
    private javax.swing.JSpinner RoomNoSpinner;
    private javax.swing.JLabel RooomNoLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel bathroomNoLabel;
    private javax.swing.JSpinner bathroomNoSpinner;
    private javax.swing.JComboBox<String> cityComboBox;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel postCodeLabel;
    private javax.swing.JTextField postCodeTextField;
    private javax.swing.JLabel propertySizeLabel;
    private javax.swing.JTextField propertySizeTextField;
    private javax.swing.JLabel propertyTypeLabel;
    private javax.swing.JComboBox<String> prpertyTypeComboBox;
    private javax.swing.JButton removeImageButton;
    private javax.swing.JButton selectImgButton;
    private javax.swing.JLabel selectImgLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration
}